server {
    listen 8099 ssl;
    server_name _;
    root /var/www/html;
    index index.html;

    ssl_certificate /ssl/self-signed/cert.pem;
    ssl_certificate_key /ssl/self-signed/key.pem;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /assets/ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    gzip on;
    gzip_types text/plain text/css application/javascript application/json image/svg+xml;
    gzip_min_length 256;
}
